kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: {{ include "jaeger.elasticsearch.fullname" . }}
  labels:
    {{- include "jaeger.elasticsearch.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.elasticsearch.replicaCount }}
  serviceName: {{ include "jaeger.elasticsearch.fullname" . }}-headless
  selector:
    matchLabels:
      {{- include "jaeger.elasticsearch.selectorLabels" . | nindent 6 }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "jaeger.elasticsearch.fullname" . }}
        labels:
          {{- include "jaeger.query.labels" . | nindent 10 }}
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  template:
    metadata:
      labels:
        {{- include "jaeger.elasticsearch.selectorLabels" . | nindent 8 }}
    spec:
      initContainers:
        - name: configure-sysctl
          image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          securityContext:
            runAsUser: 0
            privileged: true
          command:
            - sysctl
            - -w
            - vm.max_map_count={{ .Values.elasticsearch.sysVmMaxMapCount }}
      containers:
        - name: {{ include "jaeger.elasticsearch.fullname" . }}
          image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
          imagePullPolicy: {{ .Values.elasticsearch.image.pullPolicy }}
          env:
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: discovery.seed_hosts
              value: {{ include "jaeger.elasticsearch.fullname" . }}-headless
            - name: cluster.initial_master_nodes
              value: {{ include "jaeger.elasticsearch.endpoints" . }}
            - name: cluster.name
              value: {{ .Values.elasticsearch.clusterName }}
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS
              value: {{ .Values.elasticsearch.javaOpts }}
          ports:
            - name: http
              protocol: TCP
              containerPort: {{ .Values.elasticsearch.service.ports.http }}
            - name: transport
              protocol: TCP
              containerPort: {{ .Values.elasticsearch.service.ports.transport }}
          volumeMounts:
            - name: {{ include "jaeger.elasticsearch.fullname" . }}
              mountPath: /usr/share/elasticsearch/data
