version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./ssl:/ssl
      - ./conf/nginx/ext:/etc/nginx/ext
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    logging:
      driver: 'json-file'
      options:
        max-size: '256m'
  frps:
    image: snowdreamtech/frps
    volumes:
      - ./conf/frps/frps.ini:/etc/frp/frps.ini
    env_file:
      - ./envs/frps/frps.env

networks:
  default:
    external:
      name: playground
