version: '3.9'

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/ssl
    logging:
      driver: 'json-file'
      options:
        max-size: '256m'

networks:
  default:
    external:
      name: playground
