version: '3.9'

services:
  mysql:
    image: mysql
    env_file:
      - ./envs/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./conf/playground.cnf:/etc/mysql/conf.d/playground.cnf
    security_opt:
      - seccomp:unconfined

networks:
  default:
    external:
      name: playground
