kind: CronJob
apiVersion: batch/v1beta1
metadata:
  name: {{ include "jaeger.cleaner.fullname" . }}
  labels:
    {{- include "jaeger.cleaner.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cleaner.schedule }}
  jobTemplate:
    metadata:
      labels:
        {{- include "jaeger.cleaner.selectorLabels" . | nindent 8 }}
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: {{ include "jaeger.cleaner.fullname" . }}
              image: {{ .Values.cleaner.image.repository }}:{{ .Values.cleaner.image.tag | default .Chart.AppVersion }}
              imagePullPolicy: {{ .Values.cleaner.image.pullPolicy }}
              args:
                - "{{ .Values.cleaner.cleanDays }}"
                - {{ include "jaeger.elasticsearch.address" . }}
